use self::Timing::*;

pub enum Timing {
    Immediate,
    Accumulator,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    ZeroPageRmw,
    ZeroPageXRmw,
    ZeroPageSt,
    ZeroPageXSt,
    ZeroPageYSt,
    Relative,
    Absolute,
    AbsoluteJmp,
    AbsoluteX,
    AbsoluteY,
    AbsoluteRmw,
    AbsoluteXRmw,
    AbsoluteSt,
    AbsoluteXSt,
    AbsoluteYSt,
    AbsoluteYIllegal,
    Indirect,
    IndirectX,
    IndirectY,
    IndirectXSt,
    IndirectYSt,
    IndirectXIllegal,
    IndirectYIllegal,
    Implied,
    Rti,
    Rts,
    Jsr,
    Brk,
    Pha,
    Php,
    Pla,
    Plp,
}

pub static OPCODES: [(Timing, &str); 0x100] = [
    (Brk, ""),
    (IndirectX, "self.cpu_ora(val);"),
    (Immediate, "self.cpu.halt = true;"),
    (IndirectXIllegal, "self.cpu_slo();"),
    (ZeroPage, ""),
    (ZeroPage, "self.cpu_ora(val);"),
    (ZeroPageRmw, "self.cpu_asl(val);"),
    (ZeroPageRmw, "self.cpu_slo();"),
    (Php, ""),
    (Immediate, "self.cpu_ora(val);"),
    (Accumulator, "self.cpu_asl_a();"),
    (Immediate, "self.cpu_anc(val);"),
    (Absolute, ""),
    (Absolute, "self.cpu_ora(val);"),
    (AbsoluteRmw, "self.cpu_asl(val);"),
    (AbsoluteRmw, "self.cpu_slo();"),
    (Relative, "!self.cpu.n"),
    (IndirectY, "self.cpu_ora(val);"),
    (Immediate, "self.cpu.halt = true;"),
    (IndirectYIllegal, "self.cpu_slo();"),
    (ZeroPageX, ""),
    (ZeroPageX, "self.cpu_ora(val);"),
    (ZeroPageXRmw, "self.cpu_asl(val);"),
    (ZeroPageXRmw, "self.cpu_slo();"),
    (Implied, "self.cpu.c = false;"),
    (AbsoluteY, "self.cpu_ora(val);"),
    (Implied, ""),
    (AbsoluteYIllegal, "self.cpu_slo();"),
    (AbsoluteX, ""),
    (AbsoluteX, "self.cpu_ora(val);"),
    (AbsoluteXRmw, "self.cpu_asl(val);"),
    (AbsoluteXRmw, "self.cpu_slo();"),
    (Jsr, "self.cpu_jsr(val);"),
    (IndirectX, "self.cpu_and(val);"),
    (Immediate, "self.cpu.halt = true;"),
    (IndirectXIllegal, "self.cpu_rla();"),
    (ZeroPage, "self.cpu_bit(val);"),
    (ZeroPage, "self.cpu_and(val);"),
    (ZeroPageRmw, "self.cpu_rol(val);"),
    (ZeroPageRmw, "self.cpu_rla();"),
    (Plp, ""),
    (Immediate, "self.cpu_and(val);"),
    (Accumulator, "self.cpu_rol_a();"),
    (Immediate, "self.cpu_anc(val);"),
    (Absolute, "self.cpu_bit(val);"),
    (Absolute, "self.cpu_and(val);"),
    (AbsoluteRmw, "self.cpu_rol(val);"),
    (AbsoluteRmw, "self.cpu_rla();"),
    (Relative, "self.cpu.n"),
    (IndirectY, "self.cpu_and(val);"),
    (Immediate, "self.cpu.halt = true;"),
    (IndirectYIllegal, "self.cpu_rla();"),
    (ZeroPageX, ""),
    (ZeroPageX, "self.cpu_and(val);"),
    (ZeroPageXRmw, "self.cpu_rol(val);"),
    (ZeroPageXRmw, "self.cpu_rla();"),
    (Implied, "self.cpu.c = true;"),
    (AbsoluteY, "self.cpu_and(val);"),
    (Implied, ""),
    (AbsoluteYIllegal, "self.cpu_rla();"),
    (AbsoluteX, ""),
    (AbsoluteX, "self.cpu_and(val);"),
    (AbsoluteXRmw, "self.cpu_rol(val);"),
    (AbsoluteXRmw, "self.cpu_rla();"),
    (Rti, "self.cpu_rti();"),
    (IndirectX, "self.cpu_eor(val);"),
    (Immediate, "self.cpu.halt = true;"),
    (IndirectXIllegal, "self.cpu_sre();"),
    (ZeroPage, ""),
    (ZeroPage, "self.cpu_eor(val);"),
    (ZeroPageRmw, "self.cpu_lsr(val);"),
    (ZeroPageRmw, "self.cpu_sre();"),
    (Pha, ""),
    (Immediate, "self.cpu_eor(val);"),
    (Accumulator, "self.cpu_lsr_a();"),
    (Immediate, "self.cpu_alr(val);"),
    (AbsoluteJmp, ""),
    (Absolute, "self.cpu_eor(val);"),
    (AbsoluteRmw, "self.cpu_lsr(val);"),
    (AbsoluteRmw, "self.cpu_sre();"),
    (Relative, "!self.cpu.v"),
    (IndirectY, "self.cpu_eor(val);"),
    (Immediate, "self.cpu.halt = true;"),
    (IndirectYIllegal, "self.cpu_sre();"),
    (ZeroPageX, ""),
    (ZeroPageX, "self.cpu_eor(val);"),
    (ZeroPageXRmw, "self.cpu_lsr(val);"),
    (ZeroPageXRmw, "self.cpu_sre();"),
    (Implied, "self.cpu.i = false;"),
    (AbsoluteY, "self.cpu_eor(val);"),
    (Implied, ""),
    (AbsoluteYIllegal, "self.cpu_sre();"),
    (AbsoluteX, ""),
    (AbsoluteX, "self.cpu_eor(val);"),
    (AbsoluteXRmw, "self.cpu_lsr(val);"),
    (AbsoluteXRmw, "self.cpu_sre();"),
    (Rts, "self.cpu_rts();"),
    (IndirectX, "self.cpu_adc(val);"),
    (Immediate, "self.cpu.halt = true;"),
    (IndirectXIllegal, "self.cpu_rra();"),
    (ZeroPage, ""),
    (ZeroPage, "self.cpu_adc(val);"),
    (ZeroPageRmw, "self.cpu_ror(val);"),
    (ZeroPageRmw, "self.cpu_rra();"),
    (Pla, ""),
    (Immediate, "self.cpu_adc(val);"),
    (Accumulator, "self.cpu_ror_a();"),
    (Immediate, "self.cpu_arr(val);"),
    (Indirect, ""),
    (Absolute, "self.cpu_adc(val);"),
    (AbsoluteRmw, "self.cpu_ror(val);"),
    (AbsoluteRmw, "self.cpu_rra();"),
    (Relative, "self.cpu.v"),
    (IndirectY, "self.cpu_adc(val);"),
    (Immediate, "self.cpu.halt = true;"),
    (IndirectYIllegal, "self.cpu_rra();"),
    (ZeroPageX, ""),
    (ZeroPageX, "self.cpu_adc(val);"),
    (ZeroPageXRmw, "self.cpu_ror(val);"),
    (ZeroPageXRmw, "self.cpu_rra();"),
    (Implied, "self.cpu.i = true;"),
    (AbsoluteY, "self.cpu_adc(val);"),
    (Implied, ""),
    (AbsoluteYIllegal, "self.cpu_rra();"),
    (AbsoluteX, ""),
    (AbsoluteX, "self.cpu_adc(val);"),
    (AbsoluteXRmw, "self.cpu_ror(val);"),
    (AbsoluteXRmw, "self.cpu_rra();"),
    (Immediate, ""),
    (IndirectXSt, "self.cpu_sta();"),
    (Immediate, ""),
    (IndirectX, "self.cpu_aax();"),
    (ZeroPageSt, "self.cpu_sty();"),
    (ZeroPageSt, "self.cpu_sta();"),
    (ZeroPageSt, "self.cpu_stx();"),
    (ZeroPage, "self.cpu_aax();"),
    (Implied, "self.cpu_dey();"),
    (Immediate, ""),
    (Implied, "self.cpu_txa();"),
    (Immediate, "self.cpu_xaa(val);"),
    (AbsoluteSt, "self.cpu_sty();"),
    (AbsoluteSt, "self.cpu_sta();"),
    (AbsoluteSt, "self.cpu_stx();"),
    (Absolute, "self.cpu_aax();"),
    (Relative, "!self.cpu.c"),
    (IndirectYSt, "self.cpu_sta();"),
    (Immediate, "self.cpu.halt = true;"),
    (IndirectYSt, "self.cpu_ahx();"),
    (ZeroPageXSt, "self.cpu_sty();"),
    (ZeroPageXSt, "self.cpu_sta();"),
    (ZeroPageYSt, "self.cpu_stx();"),
    (ZeroPageY, "self.cpu_aax();"),
    (Implied, "self.cpu_tya();"),
    (AbsoluteYSt, "self.cpu_sta();"),
    (Implied, "self.cpu_txs();"),
    (AbsoluteYSt, "self.cpu_tas();"),
    (AbsoluteXSt, "self.cpu_shy();"),
    (AbsoluteXSt, "self.cpu_sta();"),
    (AbsoluteYSt, "self.cpu_shx();"),
    (AbsoluteYSt, "self.cpu_ahx();"),
    (Immediate, "self.cpu_ldy(val);"),
    (IndirectX, "self.cpu_lda(val);"),
    (Immediate, "self.cpu_ldx(val);"),
    (IndirectX, "self.cpu_lax(val);"),
    (ZeroPage, "self.cpu_ldy(val);"),
    (ZeroPage, "self.cpu_lda(val);"),
    (ZeroPage, "self.cpu_ldx(val);"),
    (ZeroPage, "self.cpu_lax(val);"),
    (Implied, "self.cpu_tay();"),
    (Immediate, "self.cpu_lda(val);"),
    (Implied, "self.cpu_tax();"),
    (Immediate, "self.cpu_lax(val);"),
    (Absolute, "self.cpu_ldy(val);"),
    (Absolute, "self.cpu_lda(val);"),
    (Absolute, "self.cpu_ldx(val);"),
    (Absolute, "self.cpu_lax(val);"),
    (Relative, "self.cpu.c"),
    (IndirectY, "self.cpu_lda(val);"),
    (Immediate, "self.cpu.halt = true;"),
    (IndirectY, "self.cpu_lax(val);"),
    (ZeroPageX, "self.cpu_ldy(val);"),
    (ZeroPageX, "self.cpu_lda(val);"),
    (ZeroPageY, "self.cpu_ldx(val);"),
    (ZeroPageY, "self.cpu_lax(val);"),
    (Implied, "self.cpu.v = false;"),
    (AbsoluteY, "self.cpu_lda(val);"),
    (Implied, "self.cpu_tsx();"),
    (AbsoluteY, "self.cpu_las(val);"),
    (AbsoluteX, "self.cpu_ldy(val);"),
    (AbsoluteX, "self.cpu_lda(val);"),
    (AbsoluteY, "self.cpu_ldx(val);"),
    (AbsoluteY, "self.cpu_lax(val);"),
    (Immediate, "self.cpu_cpy(val);"),
    (IndirectX, "self.cpu_cmp(val);"),
    (Immediate, ""),
    (IndirectXIllegal, "self.cpu_dcp();"),
    (ZeroPage, "self.cpu_cpy(val);"),
    (ZeroPage, "self.cpu_cmp(val);"),
    (ZeroPageRmw, "self.cpu_dec(val);"),
    (ZeroPageRmw, "self.cpu_dcp();"),
    (Implied, "self.cpu_iny();"),
    (Immediate, "self.cpu_cmp(val);"),
    (Implied, "self.cpu_dex();"),
    (Immediate, "self.cpu_axs(val);"),
    (Absolute, "self.cpu_cpy(val);"),
    (Absolute, "self.cpu_cmp(val);"),
    (AbsoluteRmw, "self.cpu_dec(val);"),
    (AbsoluteRmw, "self.cpu_dcp();"),
    (Relative, "!self.cpu.z"),
    (IndirectY, "self.cpu_cmp(val);"),
    (Immediate, "self.cpu.halt = true;"),
    (IndirectYIllegal, "self.cpu_dcp();"),
    (ZeroPageX, ""),
    (ZeroPageX, "self.cpu_cmp(val);"),
    (ZeroPageXRmw, "self.cpu_dec(val);"),
    (ZeroPageXRmw, "self.cpu_dcp();"),
    (Implied, "self.cpu.d = false;"),
    (AbsoluteY, "self.cpu_cmp(val);"),
    (Implied, ""),
    (AbsoluteYIllegal, "self.cpu_dcp();"),
    (AbsoluteX, ""),
    (AbsoluteX, "self.cpu_cmp(val);"),
    (AbsoluteXRmw, "self.cpu_dec(val);"),
    (AbsoluteXRmw, "self.cpu_dcp();"),
    (Immediate, "self.cpu_cpx(val);"),
    (IndirectX, "self.cpu_sbc(val);"),
    (Immediate, ""),
    (IndirectXIllegal, "self.cpu_isc();"),
    (ZeroPage, "self.cpu_cpx(val);"),
    (ZeroPage, "self.cpu_sbc(val);"),
    (ZeroPageRmw, "self.cpu_inc(val);"),
    (ZeroPageRmw, "self.cpu_isc();"),
    (Implied, "self.cpu_inx();"),
    (Immediate, "self.cpu_sbc(val);"),
    (Implied, ""),
    (Immediate, "self.cpu_sbc(val);"),
    (Absolute, "self.cpu_cpx(val);"),
    (Absolute, "self.cpu_sbc(val);"),
    (AbsoluteRmw, "self.cpu_inc(val);"),
    (AbsoluteRmw, "self.cpu_isc();"),
    (Relative, "self.cpu.z"),
    (IndirectY, "self.cpu_sbc(val);"),
    (Immediate, "self.cpu.halt = true;"),
    (IndirectYIllegal, "self.cpu_isc();"),
    (ZeroPageX, ""),
    (ZeroPageX, "self.cpu_sbc(val);"),
    (ZeroPageXRmw, "self.cpu_inc(val);"),
    (ZeroPageXRmw, "self.cpu_isc();"),
    (Implied, "self.cpu.d = true;"),
    (AbsoluteY, "self.cpu_sbc(val);"),
    (Implied, ""),
    (AbsoluteYIllegal, "self.cpu_isc();"),
    (AbsoluteX, ""),
    (AbsoluteX, "self.cpu_sbc(val);"),
    (AbsoluteXRmw, "self.cpu_inc(val);"),
    (AbsoluteXRmw, "self.cpu_isc();"),
];
